template layout
js-tasks-ru/htmlcss-20230124_darya94 pull request #10
Opened 2023-02-11 18:27 UTC by dariakzlv

2023-02-11 18:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 10:34 UTC, GSemikozov requested changes

2023-02-14 10:34 UTC, GSemikozov commented on components/container/container.css
> +.container_inner-page {
контейнер - это универсальный блок, но если нам нужен под конкретный случай - значит это будет элемент того блока для которого нужно такое поведение

2023-02-14 10:34 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_inner {
лучше .histogram_preview, а еще лучше - через класс-микс блока куда встраиваем (эти ограничения / отступы нам нужны ведь в одном конкретно взятом случае)

2023-02-14 18:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-16 18:53 UTC, GSemikozov approved these changes

2023-02-16 18:53 UTC, merged