styled modal
js-tasks-ru/htmlcss-20230124_darya94 pull request #13
Opened 2023-02-12 17:23 UTC by dariakzlv

2023-02-12 17:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 10:37 UTC, GSemikozov requested changes

2023-02-14 10:37 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +            <button class="button button_primary" id="modal-open">Open modal</button>
кнопка вызова модалки - это не часть самой модалки, нужно вынести наружу

2023-02-14 10:37 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +            <div class="modal__wrapper" id="modal">
id вешаем на весь блок

2023-02-14 10:37 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                    <p class="modal__title">Modal title</p>
h4

2023-02-14 10:37 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__wrapper {
лишний элемент, стили перенесем на .modal

2023-02-14 13:18 UTC, dariakzlv commented on 05-lection3/02-modal/index.html
> +            <button class="button button_primary" id="modal-open">Open modal</button>
готово

2023-02-14 13:19 UTC, dariakzlv commented on 05-lection3/02-modal/modal.css
> +.modal__wrapper {
готово

2023-02-14 13:20 UTC, dariakzlv commented on 05-lection3/02-modal/index.html
> +            <div class="modal__wrapper" id="modal">
готово

2023-02-14 13:20 UTC, dariakzlv commented on 05-lection3/02-modal/index.html
> +                    <p class="modal__title">Modal title</p>
готово

2023-02-14 13:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 18:30 UTC, GSemikozov approved these changes

2023-02-14 18:31 UTC, merged