styled accordion
js-tasks-ru/htmlcss-20230124_darya94 pull request #6
Opened 2023-02-03 09:38 UTC by dariakzlv

2023-02-03 09:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 09:47 UTC, GSemikozov requested changes

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 730px;
лишнее ограничение

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 0px 24px 32px;
справа тоже нужен

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
марджины на уровне блока задавать нельзя, предлагаю этот класс переименовать в .accordion__item, и в разметки все айтемы обернуть в общий div с классом блока .accordion

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    max-width: 650px;
лишнее

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 16px;
паддинг участвует при подсчете размеров блока, поэтому - тут лучше margin

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <main>
<div class="accordion

2023-02-03 09:47 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details open class="accordion">
accordion__item

2023-02-03 10:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 15:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-03 15:36 UTC, GSemikozov requested changes

2023-02-03 15:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion_item {
элемент - через 2 нижних подчеркивания

2023-02-03 15:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 530px 24px 32px;
справа не нужно такой огромный отступ, он будет совпадать с тем, который слева

2023-02-03 15:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +}
и еще важно что при accordion_item[open] паддинг снизу меняется

2023-02-04 09:33 UTC, dariakzlv commented on 03-lection1/02-accordion/accordion.css
> +.accordion_item {
+

2023-02-04 09:34 UTC, dariakzlv commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 530px 24px 32px;
готово

2023-02-04 09:46 UTC, dariakzlv commented on 03-lection1/02-accordion/accordion.css
> +}
готово

2023-02-05 14:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-06 09:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-08 22:26 UTC, GSemikozov approved these changes

2023-02-08 22:26 UTC, merged